library:
  visible: false
source:
  visible: true
  percentage: 0.5499951625386997
board:
  visible_edition: false
  collapse_toolbox: false
  user_permissions:
    can_change_initial_board: false
    can_change_initial_board_source: false
    can_edit_board: false
    can_view_size_section: false
    can_view_attire_section: false
    can_toggle_visibility: false
  active: 7
  initial_board_source: random
execution_speed:
  user_permissions:
    can_change_speed: true
  active: high
attire:
  user_permissions:
    can_toggle_visibility: false
  visible: true
  active: figus
initialDescription: true
link: ''
blocks:
  defaultToolbox: |
      <category name="COMANDOS">
      </category>
        <category name="Procedimientos primitivos">
          <block type="CrearAlbumDeFigus"></block>
          <block type="CrearContadorDeFigus"></block>
          <block type="ComprarFigu"></block>
          <block type="PegarFigu"></block>
          <block type="AumentarContador"></block>
        </category>
        <category name="Mis procedimientos" custom="PROCEDURE_CALLS">
        </category>
        <category name="Repeticiones">
          <block type="RepeticionSimple"></block>
          <block type="RepeticionCondicionalReal"></block>
        </category>
      <category name="EXPRESIONES">
      </category>
        <category name="Valores literales">
          <block type="math_number"></block>
        </category>
        <category name="Funciones primitivas">
          <block type="contadorCreado"></block>
        </category>
        <category name="Mis funciones" custom="FUNCTION_CALLS">
        </category>
      <category name="DEFINICIONES">
      </category>
        <category name="Procedimientos">
          <block type="procedures_defnoreturnnoparams"></block>
        </category>
        <category name="Funciones">
          <block type="procedures_defreturnsimple"></block>
        </category>
  visible:  [ "COMANDOS"
                            , "Procedimientos primitivos", "Mis procedimientos"
                            , "RepeticionSimple", "RepeticionCondicionalReal"
            , "EXPRESIONES" , "Numero"
                            , "FuncionesPrimitivas", "Mis funciones"
            , "DEFINICIONES", "procedures_defnoreturn"
                            , "procedures_defreturnsimplewithparams"
            ]
  disabled: []
activity:
  creation_mode: advanced
  construction_mode: blocks
  execution_type: sequential
name: figus 1
