name: figus
rules:
  - when:
      red: 0
      green: 0
      blue: 0
      black: 1
    image: figunueva.png
  - when:
      red: 0
      green: 0
      blue: 0
      black: 2
    image: con.png
  - when:
      red: 0
      green: 0
      blue: 0
      black: 3
    image: tador.png
    text: null
  - when:
      red: 0
      green: 1
      blue: 1
      black: 0
    image: vacia.png
    text: null
  - when:
      red: 0
      green: 0
      blue: 1
      black: 0
    image: null
    text: '0'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 1
    image: null
    text: '1'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 2
    image: null
    text: '2'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 3
    image: null
    text: '3'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 4
    image: null
    text: '4'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 5
    image: null
    text: '5'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 6
    image: null
    text: '6'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 7
    image: null
    text: '7'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 8
    image: null
    text: '8'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 9
    image: null
    text: '9'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 10
    image: null
    text: '10'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 11
    image: null
    text: '11'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 12
    image: null
    text: '12'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 13
    image: null
    text: '13'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 14
    image: null
    text: '14'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 15
    image: null
    text: '15'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 16
    image: null
    text: '16'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 17
    image: null
    text: '17'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 18
    image: null
    text: '18'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 19
    image: null
    text: '19'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 20
    image: null
    text: '20'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 21
    image: null
    text: '21'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 22
    image: null
    text: '22'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 23
    image: null
    text: '23'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 24
    image: null
    text: '24'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 25
    image: null
    text: '25'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 26
    image: null
    text: '26'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 27
    image: null
    text: '27'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 28
    image: null
    text: '28'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 29
    image: null
    text: '29'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 30
    image: null
    text: '30'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 31
    image: null
    text: '31'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 32
    image: null
    text: '32'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 33
    image: null
    text: '33'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 34
    image: null
    text: '34'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 35
    image: null
    text: '35'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 36
    image: null
    text: '36'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 37
    image: null
    text: '37'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 38
    image: null
    text: '38'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 39
    image: null
    text: '39'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 40
    image: null
    text: '40'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 41
    image: null
    text: '41'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 42
    image: null
    text: '42'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 43
    image: null
    text: '43'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 44
    image: null
    text: '44'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 45
    image: null
    text: '45'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 46
    image: null
    text: '46'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 47
    image: null
    text: '47'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 48
    image: null
    text: '48'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 49
    image: null
    text: '49'
  - when:
      red: 0
      green: 0
      blue: 1
      black: 50
    image: null
    text: '50'
  - when:
      red: '*'
      green: 0
      blue: 0
      black: 0
    image: cursor.png
    text: null
  - when:
      red: 0
      green: 1
      blue: 0
      black: 0
    image: figu0.png
    text: null
  - when:
      red: 0
      green: 2
      blue: 0
      black: 0
    image: figu1.png
    text: null
  - when:
      red: 0
      green: 3
      blue: 0
      black: 0
    image: figu2.png
    text: null
  - when:
      red: 0
      green: 4
      blue: 0
      black: 0
    image: figu3.png
    text: null
  - when:
      red: 0
      green: 5
      blue: 0
      black: 0
    image: figu4.png
    text: null
  - when:
      red: 0
      green: 6
      blue: 0
      black: 0
    image: figu5.png
    text: null
